# Stubs for cytoolz.curried (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from .exceptions import merge, merge_with

accumulate: Any
assoc: Any
assoc_in: Any
cons: Any
countby: Any
do: Any
drop: Any
excepts: Any
filter: Any
get: Any
get_in: Any
groupby: Any
interpose: Any
itemfilter: Any
itemmap: Any
iterate: Any
join: Any
keyfilter: Any
keymap: Any
map: Any
mapcat: Any
nth: Any
partial: Any
partition: Any
partition_all: Any
partitionby: Any
pluck: Any
random_sample: Any
reduce: Any
reduceby: Any
remove: Any
sliding_window: Any
sorted: Any
tail: Any
take: Any
take_nth: Any
topk: Any
unique: Any
update_in: Any
valfilter: Any
valmap: Any
