# Stubs for cytoolz.curried.exceptions (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any


def merge(d: Any, *dicts: Any, **kwargs: Any) -> Any: ...


def merge_with(func: Any, d: Any, *dicts: Any, **kwargs: Any) -> Any: ...
