# Stubs for cytoolz.recipes (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

countby: Any


class partitionby:

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    def __iter__(self) -> Any: ...

    def __next__(self) -> Any: ...

    def __reduce__(self) -> Any: ...

    def __setstate__(self, state: Any) -> Any: ...
