# Stubs for cytoolz.utils (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

consume: Any
include_dirs: Any
no_default: str
raises: Any
